# Generated by Django 3.2.5 on 2022-01-14 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_Pro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_Pro', to=settings.AUTH_USER_MODEL),
        ),
    ]
