# Generated by Django 3.2.5 on 2022-01-14 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_user_pro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_Pro',
            new_name='userPro',
        ),
    ]
