# Generated by Django 3.2.5 on 2022-01-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_user_pro_profile_userpro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contents',
            old_name='date',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='contents',
            name='num_favo',
            field=models.IntegerField(default=0),
        ),
    ]
